### ISSUE TITLE
Cow on webpack

### ISSUE THREAD

**Issue by pablo-cabrera** [Swatinem/cow#1]
Hey there, I was trying to use your library along with redux in order to copy-on-write within my reducer functions but it tries to resolve a directory named "./lib-cov" within the project, I guess it's due to the conditional require within the index.js

**Comment by Swatinem** [comment]
This was due to some really ancient code coverage tooling. It was already fixed some 3-4 years ago, but never published. I published a new version to npm.

But I would still recommend switching to something that is actually maintained. I haven’t touched this project in 3 years.
